// entrypoints/popup/Popup.svelte
<script lang="ts">
  import {
    lastSummaryErrorStore,
    savedSummariesStore,
    modelChainStore,
    modelStore,
    ongoingGenerationStore,
    type LastSummaryError,
  } from "~/util/storage"
  import { formatModelWithProvider, getConfiguredModelChain, getModelProvider, type AiProvider } from "~/util/models"
  import { getErrorMessage } from "~/util/errors"
  import { onMount } from "svelte"
  import snarkdown from "snarkdown"

  interface GetCommentsResponse {
    success?: boolean
    comments?: string
    error?: string
    details?: string
  }

  interface GenerateSummaryResponse {
    success?: boolean
    started?: boolean
    model?: string
    error?: string
    details?: string
    cancelled?: boolean
  }

  interface GenerationStatusResponse {
    success?: boolean
    active?: boolean
    model?: string
    timestamp?: number
    error?: string
    details?: string
  }

  interface RuntimeSummaryMessage {
    action?: string
    url?: string
    summary?: string
    model?: string
    provider?: AiProvider
    error?: string
    details?: string
    warning?: string
  }

  const LAST_ERROR_DISPLAY_MS = 24 * 60 * 60 * 1000

  let isLoading = $state(false)
  let buttonText = $state("Get Comments")
  let comments = $state("")
  let summary = $state("")
  let error = $state("")
  let errorDetails = $state("")
  let warning = $state("")
  let isGeneratingSummary = $state(false)
  let isCancellingSummary = $state(false)
  let currentUrl = $state("")
  let isProcessingInBackground = $state(false)
  let currentModelName = $state("")
  let currentModelProvider = $state<AiProvider | null>(null)
  let summaryCreatedBy = $state("")
  let summaryCreatedByProvider = $state<AiProvider | null>(null)
  let isValidHackerNewsUrl = $state(false)

  function checkIfHackerNewsUrl(url: string): boolean {
    return url.includes("news.ycombinator.com/item?id=")
  }

  async function loadCurrentModel() {
    const [configuredModelChain, legacyModel] = await Promise.all([modelChainStore.getValue(), modelStore.getValue()])
    const currentModel = getConfiguredModelChain(configuredModelChain, legacyModel)[0] ?? ""

    currentModelName = currentModel
    currentModelProvider = getModelProvider(currentModel)
  }

  onMount(() => {
    let isMounted = true

    const handleRuntimeMessage = (message: RuntimeSummaryMessage) => {
      if (message.url !== currentUrl) {
        return
      }

      if (message.action === "summaryComplete") {
        handleSummaryComplete(message)
      }

      if (message.action === "summaryFailed") {
        resetGenerationState()
        setErrorMessage(message.error || "Summary generation failed.", message.details)
        updateButtonText()
      }

      if (message.action === "summaryCancelled") {
        resetGenerationState()
        warning = "Summary generation was cancelled."
        updateButtonText()
      }
    }

    browser.runtime.onMessage.addListener(handleRuntimeMessage)
    void initializePopup(() => isMounted)

    return () => {
      isMounted = false
      browser.runtime.onMessage.removeListener(handleRuntimeMessage)
    }
  })

  async function initializePopup(isMounted: () => boolean) {
    try {
      const [tab] = await browser.tabs.query({ active: true, currentWindow: true })

      if (!isMounted()) {
        return
      }

      if (tab.url) {
        currentUrl = tab.url
        await loadCurrentModel()

        if (!isMounted()) {
          return
        }

        isValidHackerNewsUrl = checkIfHackerNewsUrl(tab.url)
        if (isValidHackerNewsUrl) {
          await loadCachedSummary(tab.url)
          const hasActiveGeneration = await checkOngoingGeneration()

          if (!hasActiveGeneration) {
            await loadLastSummaryError(tab.url)
          }
        }
        updateButtonText()
      } else {
        setErrorMessage("No URL found for the current tab.")
      }
    } catch (err) {
      setErrorFromUnknown(err, "Failed to load popup state.")
      console.error("Error loading popup state:", err)
    }
  }

  async function loadCachedSummary(url: string): Promise<boolean> {
    try {
      const savedSummaries = await savedSummariesStore.getValue()
      const cachedSummary = savedSummaries.find(item => item.id === url)

      if (cachedSummary?.summary?.trim()) {
        summary = cachedSummary.summary
        summaryCreatedBy = cachedSummary.createdBy
        summaryCreatedByProvider =
          (cachedSummary.provider as AiProvider | undefined) || getModelProvider(cachedSummary.createdBy)
        console.log("Loaded cached summary for:", url)
        return true
      }
    } catch (err) {
      warning = `Cached summary could not be loaded: ${getErrorMessage(err)}`
      console.error("Error loading cached summary:", err)
    }

    return false
  }

  async function loadLastSummaryError(url: string) {
    try {
      const lastError = await lastSummaryErrorStore.getValue()

      if (lastError?.url === url && lastError.timestamp > Date.now() - LAST_ERROR_DISPLAY_MS) {
        setErrorMessage(lastError.message, lastError.details)
      }
    } catch (err) {
      console.error("Error loading last summary error:", err)
    }
  }

  function updateButtonText() {
    if (!isValidHackerNewsUrl) {
      buttonText = "Not a Hacker News Page"
    } else if (isLoading) {
      buttonText = "Loading..."
    } else if (isGeneratingSummary || isProcessingInBackground) {
      buttonText = "Generating..."
    } else if (summary?.trim()) {
      buttonText = "Regenerate Summary"
    } else {
      buttonText = "Generate Summary"
    }
  }

  async function checkOngoingGeneration(): Promise<boolean> {
    try {
      const status = await withTimeout(
        browser.runtime.sendMessage({
          action: "getGenerationStatus",
          url: currentUrl,
        }) as Promise<GenerationStatusResponse>,
        5000,
        "Timed out while checking summary generation status.",
      )

      if (!status?.success) {
        setErrorMessage(status?.error || "Failed to check summary generation status.", status?.details)
        resetGenerationState()
        return false
      }

      if (status.active && status.model) {
        isProcessingInBackground = true
        isGeneratingSummary = true
        currentModelName = status.model
        currentModelProvider = getModelProvider(status.model)
        updateButtonText()
        return true
      }

      resetGenerationState()

      if (status.error) {
        setErrorMessage(status.error, status.details)
      }

      return false
    } catch (err) {
      const ongoing = await ongoingGenerationStore.getValue()

      if (ongoing && ongoing.url === currentUrl && ongoing.timestamp > Date.now() - 300000) {
        isProcessingInBackground = true
        isGeneratingSummary = true
        currentModelName = ongoing.model
        currentModelProvider = getModelProvider(ongoing.model)
        warning = "Could not confirm the background job status. If this stays stuck, cancel and try again."
        updateButtonText()
        return true
      }

      setErrorFromUnknown(err, "Failed to check summary generation status.")
      console.error("Error checking ongoing generation:", err)
      return false
    }
  }

  async function getComments() {
    isLoading = true
    updateButtonText()
    clearMessages()

    try {
      const [tab] = await browser.tabs.query({ active: true, currentWindow: true })

      if (!tab.id) {
        setErrorMessage("No active tab found.")
        return
      }

      if (!tab.url) {
        setErrorMessage("No URL found for the current tab.")
        return
      }

      currentUrl = tab.url
      isValidHackerNewsUrl = checkIfHackerNewsUrl(tab.url)

      if (!isValidHackerNewsUrl) {
        setErrorMessage("Open a Hacker News submission page before generating a summary.", "", "getComments")
        return
      }

      await loadCachedSummary(tab.url)

      const contentResponse = await withTimeout(
        browser.tabs.sendMessage(tab.id, { action: "getComments" }) as Promise<GetCommentsResponse>,
        8000,
        "Timed out while reading comments from the page. Reload the Hacker News tab and try again.",
      )

      if (contentResponse?.success && typeof contentResponse.comments === "string" && contentResponse.comments.trim()) {
        comments = contentResponse.comments
        console.log("Comments received:", contentResponse.comments)

        isProcessingInBackground = true
        isGeneratingSummary = true
        await loadCurrentModel()

        const backgroundResponse = await withTimeout(
          browser.runtime.sendMessage({
            action: "generateSummary",
            comments: contentResponse.comments,
            url: tab.url,
          }) as Promise<GenerateSummaryResponse>,
          10000,
          "Timed out while starting summary generation. Please try again.",
        )

        if (!backgroundResponse?.success) {
          resetGenerationState()
          if (!backgroundResponse?.cancelled) {
            setErrorMessage(
              backgroundResponse?.error || "Failed to generate summary.",
              backgroundResponse?.details,
              "generateSummary",
            )
          }
          return
        }

        if (backgroundResponse.model) {
          currentModelName = backgroundResponse.model
          currentModelProvider = getModelProvider(backgroundResponse.model)
        }

        console.log("Summary generation started in background")
      } else {
        setErrorMessage(contentResponse?.error || "Failed to get comments.", contentResponse?.details, "getComments")
        console.error("Error getting comments:", contentResponse?.error)
      }
    } catch (err) {
      resetGenerationState()
      setErrorFromUnknown(err, "Failed to read comments or start summary generation.", "getComments")
      console.error("Error:", err)
    } finally {
      isLoading = false
      updateButtonText()
    }
  }

  async function cancelSummaryGeneration() {
    if (!currentUrl || isCancellingSummary) {
      return
    }

    isCancellingSummary = true
    clearMessages()

    try {
      const response = await withTimeout(
        browser.runtime.sendMessage({
          action: "cancelSummaryGeneration",
          url: currentUrl,
        }) as Promise<GenerateSummaryResponse>,
        5000,
        "Timed out while cancelling summary generation.",
      )

      await ongoingGenerationStore.setValue(null)
      isProcessingInBackground = false
      isGeneratingSummary = false

      if (!response?.success && response?.error) {
        warning = response.error
      }
    } catch (err) {
      setErrorFromUnknown(err, "Failed to cancel summary generation.", "cancelSummaryGeneration")
      console.error("Error cancelling summary generation:", err)
    } finally {
      isCancellingSummary = false
      updateButtonText()
    }
  }

  function openOptions() {
    void browser.runtime.openOptionsPage().catch(err => {
      setErrorFromUnknown(err, "Failed to open options page.")
    })
  }

  function getCurrentModelLabel(): string {
    return currentModelName ? formatModelWithProvider(currentModelName, currentModelProvider) : "Loading..."
  }

  function getSummaryCreatedByLabel(): string {
    return summaryCreatedBy ? formatModelWithProvider(summaryCreatedBy, summaryCreatedByProvider) : ""
  }

  function getExtensionVersion(): string {
    return browser.runtime.getManifest().version
  }

  function handleSummaryComplete(message: RuntimeSummaryMessage) {
    if (!message.summary?.trim()) {
      resetGenerationState()
      setErrorMessage("Summary generation completed, but the response was empty.")
      updateButtonText()
      return
    }

    summary = message.summary
    summaryCreatedBy = message.model || currentModelName
    summaryCreatedByProvider = message.provider || getModelProvider(summaryCreatedBy)
    currentModelName = message.model || currentModelName
    currentModelProvider = message.provider || getModelProvider(currentModelName)
    warning = message.warning || ""
    error = ""
    errorDetails = ""
    resetGenerationState()
    updateButtonText()
    console.log("Summary completed in background:", message.summary)
  }

  function resetGenerationState() {
    isProcessingInBackground = false
    isGeneratingSummary = false
    isCancellingSummary = false
  }

  function clearMessages() {
    error = ""
    errorDetails = ""
    warning = ""
  }

  function setErrorMessage(message: string, details = "", action?: LastSummaryError["action"]) {
    error = message
    errorDetails = details

    if (action && currentUrl) {
      void rememberLastSummaryError(action, message, details)
    }
  }

  function setErrorFromUnknown(err: unknown, fallback: string, action?: LastSummaryError["action"]) {
    error = getErrorMessage(err, fallback)
    errorDetails = err instanceof Error ? err.stack || err.message : ""

    if (action && currentUrl) {
      void rememberLastSummaryError(action, error, errorDetails)
    }
  }

  async function rememberLastSummaryError(action: LastSummaryError["action"], message: string, details = "") {
    try {
      await lastSummaryErrorStore.setValue({
        url: currentUrl,
        action,
        message,
        details,
        timestamp: Date.now(),
      })
    } catch (err) {
      console.warn("Failed to store popup error details:", err)
    }
  }

  async function withTimeout<T>(promise: Promise<T>, timeoutMs: number, timeoutMessage: string): Promise<T> {
    let timer: ReturnType<typeof setTimeout> | undefined

    try {
      return await Promise.race([
        promise,
        new Promise<T>((_, reject) => {
          timer = setTimeout(() => reject(new Error(timeoutMessage)), timeoutMs)
        }),
      ])
    } finally {
      if (timer) {
        clearTimeout(timer)
      }
    }
  }
</script>

<main class="p-4 min-w-[350px] max-w-[500px]">
  <h1 class="text-2xl font-bold mb-4">HN Comments Summarizer</h1>

  <!-- Current Model Info -->
  <div class="mb-4 p-2 bg-gray-50 border border-gray-200 rounded-lg">
    <p class="text-xs text-gray-600">
      Current model: <span class="font-medium text-gray-800">{getCurrentModelLabel()}</span>
    </p>
  </div>

  <!-- URL Validation Warning -->
  {#if !isValidHackerNewsUrl && currentUrl}
    <div class="mb-4 p-3 bg-yellow-100 border border-yellow-400 text-yellow-700 rounded-lg">
      <p class="font-semibold text-sm">⚠️ Not a Hacker News Submission</p>
      <p class="text-xs mt-1">
        This extension only works on Hacker News submission pages (news.ycombinator.com/item?id=)
      </p>
    </div>
  {/if}

  <div class="space-y-3 mb-4">
    <button
      onclick={getComments}
      disabled={isLoading || isGeneratingSummary || isProcessingInBackground || !isValidHackerNewsUrl}
      class="w-full bg-blue-500 hover:bg-blue-600 disabled:bg-blue-300
      text-white font-semibold py-2 px-4 rounded transition-colors"
    >
      {buttonText}
    </button>

    {#if isGeneratingSummary || isProcessingInBackground}
      <button
        onclick={cancelSummaryGeneration}
        disabled={isCancellingSummary}
        class="w-full bg-red-600 hover:bg-red-700 disabled:bg-red-300 text-white font-semibold py-2 px-4 rounded transition-colors"
      >
        {isCancellingSummary ? "Cancelling..." : "Cancel Generation"}
      </button>
    {/if}

    <button
      onclick={openOptions}
      class="w-full bg-gray-600 hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded transition-colors"
    >
      Options
    </button>

    <p class="text-center text-[11px] text-gray-400">v{getExtensionVersion()}</p>
  </div>

  <!-- Error Display -->
  {#if error}
    <div class="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg">
      <p class="font-semibold">Error:</p>
      <p class="text-sm">{error}</p>
      {#if errorDetails}
        <details class="mt-2 text-xs">
          <summary class="cursor-pointer font-medium">Details</summary>
          <pre
            class="mt-2 max-h-32 overflow-auto whitespace-pre-wrap break-words rounded bg-red-50 p-2 text-[11px]">{errorDetails}</pre>
        </details>
      {/if}
    </div>
  {/if}

  {#if warning}
    <div class="mb-4 p-3 bg-yellow-100 border border-yellow-400 text-yellow-800 rounded-lg">
      <p class="font-semibold">Notice:</p>
      <p class="text-sm">{warning}</p>
    </div>
  {/if}

  <!-- Loading States -->
  {#if isProcessingInBackground}
    <div class="mb-4 p-3 bg-green-100 border border-green-400 text-green-700 rounded-lg">
      <p class="text-sm font-medium">Generating using {currentModelName ? getCurrentModelLabel() : "AI"}...</p>
      <p class="text-xs mt-1 opacity-80">Processing in background. You can close this window.</p>
    </div>
  {/if}

  {#if isGeneratingSummary && !isProcessingInBackground}
    <div class="mb-4 p-3 bg-blue-100 border border-blue-400 text-blue-700 rounded-lg">
      <p class="text-sm font-medium">Generating summary using {currentModelName ? getCurrentModelLabel() : "AI"}...</p>
    </div>
  {/if}

  <!-- Summary Display -->
  {#if summary}
    <div class="mb-4">
      <div class="flex items-center justify-between mb-2">
        <h2 class="text-lg font-semibold">Summary</h2>
        {#if summaryCreatedBy}
          <span class="text-xs text-gray-500">Created by {getSummaryCreatedByLabel()}</span>
        {/if}
      </div>
      <div class="p-3 bg-gray-100 rounded-lg text-sm text-gray-800 prose prose-sm max-w-none">
        {@html snarkdown(summary)}
      </div>
    </div>
  {/if}

  <!-- Comments Display (for debugging) -->
  {#if comments && !summary}
    <div class="mb-4">
      <h2 class="text-lg font-semibold mb-2">Comments ({comments.length} chars)</h2>
      <div class="p-3 bg-gray-50 rounded-lg text-xs text-gray-600 max-h-40 overflow-y-auto">
        {comments.slice(0, 200)}{comments.length > 200 ? "..." : ""}
      </div>
    </div>
  {/if}
</main>

// entrypoints/popup/Popup.tsx
import {
  customGoogleModelsStore,
  hiddenGoogleModelsStore,
  lastSummaryErrorStore,
  savedSummariesStore,
  modelChainStore,
  modelStore,
  ongoingGenerationStore,
  type GenerationErrorHistoryItem,
  type LastSummaryError,
} from "~/util/storage"
import { formatModelWithProvider, getConfiguredModelChain, getModelProvider, type AiProvider } from "~/util/models"
import { getErrorMessage } from "~/util/errors"
import { createSignal, onCleanup, onMount, Show } from "solid-js"
import ActionButtons from "./components/ActionButtons"
import ErrorPanel from "./components/ErrorPanel"
import StatusPanels from "./components/StatusPanels"
import SummaryCard from "./components/SummaryCard"
import { getExtensionVersion } from "~/util/format"

interface GetCommentsResponse {
  success?: boolean
  comments?: string
  storyTitle?: string
  storyUrl?: string
  storyExcerpt?: string
  storyExcerptSkipped?: boolean
  error?: string
  details?: string
}

interface GenerateSummaryResponse {
  success?: boolean
  started?: boolean
  model?: string
  error?: string
  details?: string
  cancelled?: boolean
}

interface GenerationStatusResponse {
  success?: boolean
  active?: boolean
  model?: string
  timestamp?: number
  error?: string
  details?: string
  errorHistory?: GenerationErrorHistoryItem[]
}

interface RuntimeSummaryMessage {
  action?: string
  url?: string
  summary?: string
  model?: string
  provider?: AiProvider
  withContext?: boolean
  error?: string
  details?: string
  warning?: string
  errorHistory?: GenerationErrorHistoryItem[]
}

const LAST_ERROR_DISPLAY_MS = 24 * 60 * 60 * 1000

function checkIfHackerNewsUrl(url: string): boolean {
  return url.includes("news.ycombinator.com/item?id=")
}

export default function Popup() {
  const [isLoading, setIsLoading] = createSignal(false)
  const [comments, setComments] = createSignal("")
  const [summary, setSummary] = createSignal("")
  const [summaryWithContext, setSummaryWithContext] = createSignal(false)
  const [error, setError] = createSignal("")
  const [errorDetails, setErrorDetails] = createSignal("")
  const [warning, setWarning] = createSignal("")
  const [isGeneratingSummary, setIsGeneratingSummary] = createSignal(false)
  const [isCancellingSummary, setIsCancellingSummary] = createSignal(false)
  const [currentUrl, setCurrentUrl] = createSignal("")
  const [isProcessingInBackground, setIsProcessingInBackground] = createSignal(false)
  const [currentModelName, setCurrentModelName] = createSignal("")
  const [currentModelProvider, setCurrentModelProvider] = createSignal<AiProvider | null>(null)
  const [summaryCreatedBy, setSummaryCreatedBy] = createSignal("")
  const [summaryCreatedByProvider, setSummaryCreatedByProvider] = createSignal<AiProvider | null>(null)
  const [isValidHackerNewsUrl, setIsValidHackerNewsUrl] = createSignal(false)
  const [generationErrorHistory, setGenerationErrorHistory] = createSignal<GenerationErrorHistoryItem[]>([])

  const isBusy = () => isLoading() || isGeneratingSummary() || isProcessingInBackground()
  const currentModelLabel = () =>
    currentModelName() ? formatModelWithProvider(currentModelName(), currentModelProvider()) : "Loading..."
  const summaryCreatedByLabel = () =>
    summaryCreatedBy() ? formatModelWithProvider(summaryCreatedBy(), summaryCreatedByProvider()) : ""
  const buttonText = () => {
    if (!isValidHackerNewsUrl()) {
      return "Not a Hacker News Page"
    }

    if (isLoading()) {
      return "Loading..."
    }

    if (isGeneratingSummary() || isProcessingInBackground()) {
      return "Generating..."
    }

    if (summary().trim()) {
      return "Regenerate Summary"
    }

    return "Generate Summary"
  }
  const buttonTextWithContext = () => {
    if (!isValidHackerNewsUrl()) {
      return "Not a Hacker News Page"
    }

    if (isLoading()) {
      return "Loading..."
    }

    if (isGeneratingSummary() || isProcessingInBackground()) {
      return "Generating..."
    }

    if (summary().trim()) {
      return "Regenerate with Context"
    }

    return "Generate Summary with Context"
  }

  async function loadCurrentModel() {
    const [configuredModelChain, legacyModel, customGoogleModels, hiddenGoogleModels] = await Promise.all([
      modelChainStore.getValue(),
      modelStore.getValue(),
      customGoogleModelsStore.getValue(),
      hiddenGoogleModelsStore.getValue(),
    ])
    const currentModel =
      getConfiguredModelChain(configuredModelChain, legacyModel, customGoogleModels, hiddenGoogleModels)[0] ?? ""

    setCurrentModelName(currentModel)
    setCurrentModelProvider(getModelProvider(currentModel))
  }

  async function getActiveTab() {
    const tabs = await browser.tabs.query({ active: true, currentWindow: true })

    return tabs[0]
  }

  async function initializePopup(isMounted: () => boolean) {
    try {
      const tab = await getActiveTab()

      if (!isMounted()) {
        return
      }

      if (tab?.url) {
        setCurrentUrl(tab.url)
        await loadCurrentModel()

        if (!isMounted()) {
          return
        }

        setIsValidHackerNewsUrl(checkIfHackerNewsUrl(tab.url))
        if (isValidHackerNewsUrl()) {
          await loadCachedSummary(tab.url)
          const hasActiveGeneration = await checkOngoingGeneration()

          if (!hasActiveGeneration) {
            await loadLastSummaryError(tab.url)
          }
        }
      } else {
        setErrorMessage("No URL found for the current tab.")
      }
    } catch (err) {
      setErrorFromUnknown(err, "Failed to load popup state.")
      console.error("Error loading popup state:", err)
    }
  }

  async function loadCachedSummary(url: string): Promise<boolean> {
    try {
      const savedSummaries = await savedSummariesStore.getValue()
      const cachedSummary = savedSummaries.find(item => item.id === url)

      if (cachedSummary?.summary?.trim()) {
        setSummary(cachedSummary.summary)
        setSummaryWithContext(cachedSummary.withContext === true)
        setSummaryCreatedBy(cachedSummary.createdBy)
        setSummaryCreatedByProvider(
          (cachedSummary.provider as AiProvider | undefined) || getModelProvider(cachedSummary.createdBy),
        )
        console.log("Loaded cached summary for:", url)
        return true
      }
    } catch (err) {
      setWarning(`Cached summary could not be loaded: ${getErrorMessage(err)}`)
      console.error("Error loading cached summary:", err)
    }

    return false
  }

  async function loadLastSummaryError(url: string) {
    try {
      const lastError = await lastSummaryErrorStore.getValue()

      if (lastError?.url === url && lastError.timestamp > Date.now() - LAST_ERROR_DISPLAY_MS) {
        setErrorMessage(lastError.message, lastError.details)
      }
    } catch (err) {
      console.error("Error loading last summary error:", err)
    }
  }

  async function checkOngoingGeneration(): Promise<boolean> {
    try {
      const status = await withTimeout(
        browser.runtime.sendMessage({
          action: "getGenerationStatus",
          url: currentUrl(),
        }) as Promise<GenerationStatusResponse>,
        5000,
        "Timed out while checking summary generation status.",
      )

      if (!status?.success) {
        setErrorMessage(status?.error || "Failed to check summary generation status.", status?.details)
        resetGenerationState()
        return false
      }

      if (status.active && status.model) {
        setIsProcessingInBackground(true)
        setIsGeneratingSummary(true)
        setCurrentModelName(status.model)
        setCurrentModelProvider(getModelProvider(status.model))
        setGenerationErrorHistory(status.errorHistory ?? [])
        return true
      }

      resetGenerationState()

      if (status.error) {
        setErrorMessage(status.error, status.details)
      }

      return false
    } catch (err) {
      const ongoing = await ongoingGenerationStore.getValue()

      if (ongoing && ongoing.url === currentUrl() && ongoing.timestamp > Date.now() - 300000) {
        setIsProcessingInBackground(true)
        setIsGeneratingSummary(true)
        setCurrentModelName(ongoing.model)
        setCurrentModelProvider(getModelProvider(ongoing.model))
        setGenerationErrorHistory(ongoing.errorHistory ?? [])
        setWarning("Could not confirm the background job status. If this stays stuck, cancel and try again.")
        return true
      }

      setErrorFromUnknown(err, "Failed to check summary generation status.")
      console.error("Error checking ongoing generation:", err)
      return false
    }
  }

  async function getComments(withContext = false) {
    setIsLoading(true)
    clearMessages()

    try {
      const tab = await getActiveTab()

      if (!tab) {
        setErrorMessage("No active tab found.")
        return
      }

      if (tab.id === undefined) {
        setErrorMessage("No active tab found.")
        return
      }

      if (!tab.url) {
        setErrorMessage("No URL found for the current tab.")
        return
      }

      setCurrentUrl(tab.url)
      setIsValidHackerNewsUrl(checkIfHackerNewsUrl(tab.url))

      if (!isValidHackerNewsUrl()) {
        setErrorMessage("Open a Hacker News submission page before generating a summary.", "", "getComments")
        return
      }

      await loadCachedSummary(tab.url)

      const contentResponse = await withTimeout(
        browser.tabs.sendMessage(tab.id, { action: "getComments", withContext }) as Promise<GetCommentsResponse>,
        withContext ? 25000 : 8000,
        "Timed out while reading comments from the page. Reload the Hacker News tab and try again.",
      )

      if (contentResponse?.success && typeof contentResponse.comments === "string" && contentResponse.comments.trim()) {
        setComments(contentResponse.comments)
        console.log("Comments received:", contentResponse.comments)

        setIsProcessingInBackground(true)
        setIsGeneratingSummary(true)
        await loadCurrentModel()

        const backgroundResponse = await withTimeout(
          browser.runtime.sendMessage({
            action: "generateSummary",
            comments: contentResponse.comments,
            url: tab.url,
            withContext,
            storyTitle: contentResponse.storyTitle ?? "",
            storyUrl: contentResponse.storyUrl ?? "",
            storyExcerpt: contentResponse.storyExcerpt ?? "",
            storyExcerptSkipped: contentResponse.storyExcerptSkipped ?? true,
          }) as Promise<GenerateSummaryResponse>,
          10000,
          "Timed out while starting summary generation. Please try again.",
        )

        if (!backgroundResponse?.success) {
          resetGenerationState()
          if (!backgroundResponse?.cancelled) {
            setErrorMessage(
              backgroundResponse?.error || "Failed to generate summary.",
              backgroundResponse?.details,
              "generateSummary",
            )
          }
          return
        }

        if (backgroundResponse.model) {
          setCurrentModelName(backgroundResponse.model)
          setCurrentModelProvider(getModelProvider(backgroundResponse.model))
        }

        console.log("Summary generation started in background")
      } else {
        setErrorMessage(contentResponse?.error || "Failed to get comments.", contentResponse?.details, "getComments")
        console.error("Error getting comments:", contentResponse?.error)
      }
    } catch (err) {
      resetGenerationState()
      setErrorFromUnknown(err, "Failed to read comments or start summary generation.", "getComments")
      console.error("Error:", err)
    } finally {
      setIsLoading(false)
    }
  }

  async function cancelSummaryGeneration() {
    if (!currentUrl() || isCancellingSummary()) {
      return
    }

    setIsCancellingSummary(true)
    clearMessages()

    try {
      const response = await withTimeout(
        browser.runtime.sendMessage({
          action: "cancelSummaryGeneration",
          url: currentUrl(),
        }) as Promise<GenerateSummaryResponse>,
        5000,
        "Timed out while cancelling summary generation.",
      )

      await ongoingGenerationStore.setValue(null)
      setIsProcessingInBackground(false)
      setIsGeneratingSummary(false)

      if (!response?.success && response?.error) {
        setWarning(response.error)
      }
    } catch (err) {
      setErrorFromUnknown(err, "Failed to cancel summary generation.", "cancelSummaryGeneration")
      console.error("Error cancelling summary generation:", err)
    } finally {
      setIsCancellingSummary(false)
    }
  }

  function openOptions() {
    void browser.runtime.openOptionsPage().catch(err => {
      setErrorFromUnknown(err, "Failed to open options page.")
    })
  }

  function handleSummaryComplete(message: RuntimeSummaryMessage) {
    if (!message.summary?.trim()) {
      resetGenerationState()
      setErrorMessage("Summary generation completed, but the response was empty.")
      return
    }

    setSummary(message.summary)
    setSummaryWithContext(message.withContext === true)
    setSummaryCreatedBy(message.model || currentModelName())
    setSummaryCreatedByProvider(message.provider || getModelProvider(summaryCreatedBy()))
    setCurrentModelName(message.model || currentModelName())
    setCurrentModelProvider(message.provider || getModelProvider(currentModelName()))
    setWarning(message.warning || "")
    setError("")
    setErrorDetails("")
    resetGenerationState()
    console.log("Summary completed in background:", message.summary)
  }

  function resetGenerationState() {
    setIsProcessingInBackground(false)
    setIsGeneratingSummary(false)
    setIsCancellingSummary(false)
    setGenerationErrorHistory([])
  }

  function clearMessages() {
    setError("")
    setErrorDetails("")
    setWarning("")
    setGenerationErrorHistory([])
  }

  function setErrorMessage(message: string, details = "", action?: LastSummaryError["action"]) {
    setError(message)
    setErrorDetails(details)

    if (action && currentUrl()) {
      void rememberLastSummaryError(action, message, details)
    }
  }

  function setErrorFromUnknown(err: unknown, fallback: string, action?: LastSummaryError["action"]) {
    setError(getErrorMessage(err, fallback))
    setErrorDetails(err instanceof Error ? err.stack || err.message : "")

    if (action && currentUrl()) {
      void rememberLastSummaryError(action, error(), errorDetails())
    }
  }

  async function rememberLastSummaryError(action: LastSummaryError["action"], message: string, details = "") {
    try {
      await lastSummaryErrorStore.setValue({
        url: currentUrl(),
        action,
        message,
        details,
        timestamp: Date.now(),
      })
    } catch (err) {
      console.warn("Failed to store popup error details:", err)
    }
  }

  async function withTimeout<T>(promise: Promise<T>, timeoutMs: number, timeoutMessage: string): Promise<T> {
    let timer: ReturnType<typeof setTimeout> | undefined

    try {
      return await Promise.race([
        promise,
        new Promise<T>((_, reject) => {
          timer = setTimeout(() => reject(new Error(timeoutMessage)), timeoutMs)
        }),
      ])
    } finally {
      if (timer) {
        clearTimeout(timer)
      }
    }
  }

  onMount(() => {
    let isMounted = true

    const handleRuntimeMessage = (message: RuntimeSummaryMessage) => {
      if (message.url !== currentUrl()) {
        return
      }

      if (message.action === "summaryComplete") {
        handleSummaryComplete(message)
      }

      if (message.action === "generationUpdated") {
        if (message.model) {
          setCurrentModelName(message.model)
          setCurrentModelProvider(getModelProvider(message.model))
        }

        setGenerationErrorHistory(message.errorHistory ?? [])
      }

      if (message.action === "summaryFailed") {
        resetGenerationState()
        setErrorMessage(message.error || "Summary generation failed.", message.details)
      }

      if (message.action === "summaryCancelled") {
        resetGenerationState()
        setWarning("Summary generation was cancelled.")
      }
    }

    browser.runtime.onMessage.addListener(handleRuntimeMessage)
    void initializePopup(() => isMounted)

    onCleanup(() => {
      isMounted = false
      browser.runtime.onMessage.removeListener(handleRuntimeMessage)
    })
  })

  return (
    <main class="min-w-107.5 max-w-155 bg-zinc-950 p-4 text-zinc-100">
      <header class="mb-3 flex items-center gap-2.5">
        <span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-orange-600 text-base font-bold text-white">
          Y
        </span>
        <div class="min-w-0 flex-1">
          <h1 class="text-base leading-tight font-bold">HN Comments Summarizer</h1>
          <p class="text-[11px] text-zinc-500">v{getExtensionVersion()}</p>
        </div>
      </header>

      <div class="mb-3 rounded-xl border border-zinc-800 bg-zinc-900/60 px-3 py-2">
        <p class="text-xs text-zinc-400">
          Current model: <span class="font-medium text-zinc-100">{currentModelLabel()}</span>
        </p>
      </div>

      <Show when={!isValidHackerNewsUrl() && currentUrl()}>
        <div class="mb-3 rounded-xl border border-amber-800 bg-amber-950/60 p-3 text-amber-200">
          <p class="text-sm font-semibold">⚠️ Not a Hacker News Submission</p>
          <p class="mt-1 text-xs">
            This extension only works on Hacker News submission pages (news.ycombinator.com/item?id=)
          </p>
        </div>
      </Show>

      <div class="mb-3">
        <ActionButtons
          buttonText={buttonText()}
          buttonTextWithContext={buttonTextWithContext()}
          disabled={isBusy() || !isValidHackerNewsUrl()}
          isBusy={isGeneratingSummary() || isProcessingInBackground()}
          isCancelling={isCancellingSummary()}
          onGenerate={getComments}
          onCancel={cancelSummaryGeneration}
          onOpenOptions={openOptions}
        />
      </div>

      <div class="space-y-3">
        <Show when={error()}>
          <ErrorPanel error={error()} errorDetails={errorDetails()} />
        </Show>

        <StatusPanels
          warning={warning()}
          isProcessingInBackground={isProcessingInBackground()}
          isGeneratingSummary={isGeneratingSummary()}
          currentModelName={currentModelName()}
          currentModelLabel={currentModelLabel()}
          generationErrorHistory={generationErrorHistory()}
        />

        <Show when={summary()}>
          <SummaryCard
            summary={summary()}
            withContext={summaryWithContext()}
            createdByLabel={summaryCreatedByLabel()}
          />
        </Show>

        <Show when={comments() && !summary()}>
          <div>
            <h2 class="mb-2 text-sm font-semibold text-zinc-300">Comments ({comments().length} chars)</h2>
            <div class="max-h-40 overflow-y-auto rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-xs text-zinc-400">
              {comments().slice(0, 200)}
              {comments().length > 200 ? "..." : ""}
            </div>
          </div>
        </Show>
      </div>
    </main>
  )
}
